name: Deploy to Pages

on:
  push:
    branches:
      - mainnn
    paths-ignore:
    - README.md
    - .gitignore
    - License
    - .gitattributes
    - package.json
    - '.github/workflows/github-release.yaml'
    - '.github/workflows/nocommit-release.yaml'
    - '.github/workflows/semantic-release.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.2.1
        with:
          hugo-version: 'latest'
        #  extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
