name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
    - README.md
    - .gitignore
    - License
    - .gitattributes
    - '.github/workflows/deploy.yaml'
    - '.github/workflows/github-release.yaml'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release